timer.Simple(1.1, function()  
    scripted_ents.Alias ( "gmod_track_signal", "gmod_track_signal_new" )
    scripted_ents.Alias ( "gmod_track_signs", "gmod_track_signs_new" )
    scripted_ents.Alias("gmod_scb_autostop", "gmod_vitromod_autostop")
end)